// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Quote struct {
	ID     *string `json:"id"`
	Author string  `json:"author"`
	Quote  string  `json:"quote"`
}

type QuoteInput struct {
	Author string `json:"author"`
	Quote  string `json:"quote"`
}
